[package]
name = "bread"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.48", features = ["derive"]}
pulldown-cmark = "0.13.0"
serde = {version = "1.0.228", features=["derive"]}
tinytemplate = "1.2.1"
